### PR TITLE
Re-export helpers from index

### PR DESCRIPTION
**Pull request by charlesfries**
Before

```js
import min from 'ember-math-helpers/helpers/min';
import max from 'ember-math-helpers/helpers/max';
```

After

```js
import { min, max } from 'ember-math-helpers';
```

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
@charlesfries I am not sure I love manually updating a file to import from. What is the benefit of making this change?

**Comment by charlesfries** [comment]
@RobbieTheWagner Just makes it marginally easier to import the helpers while using strict mode/template imports. And yeah I get that concern--maybe we could dynamically generate the file.

Regardless here are some examples of this feature from other addons:

https://github.com/jmurphyau/ember-truth-helpers/blob/master/packages/ember-truth-helpers/src/index.ts

https://github.com/ember-intl/ember-intl/blob/main/packages/ember-intl/addon/index.ts

https://github.com/trusted-american/design-system/blob/master/addon/index.ts

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
> @RobbieTheWagner Just makes it marginally easier to import the helpers while using strict mode/template imports. And yeah I get that concern--maybe we could dynamically generate the file.
> 
> Regardless here are some examples of this feature from other addons:
> 
> https://github.com/jmurphyau/ember-truth-helpers/blob/master/packages/ember-truth-helpers/src/index.ts
> 
> https://github.com/ember-intl/ember-intl/blob/main/packages/ember-intl/addon/index.ts
> 
> https://github.com/trusted-american/design-system/blob/master/addon/index.ts

Fair enough. It doesn't hurt anything to include this. Should we mention this in the docs?

**Comment by charlesfries** [comment]
Added docs for this as well as the template registry. I can break the latter out into a separate PR if you'd prefer

**Comment by RobbieTheWagner** [comment]
Thanks for the PR!

**Pull request merged**
